# Generated by Django 6.0 on 2025-12-18 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_caducidad', models.DateField()),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productocatalogo')),
                ('manifiesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='inventario.manifiesto')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
