# Generated by Django 6.0 on 2025-12-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_productocatalogo_productoinventario_delete_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiesto',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
