# Generated by Django 6.0 on 2025-12-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_manifiesto_cerrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('VENTA', 'Venta'), ('MERMA', 'Merma/Dañado'), ('TRANSFERENCIA', 'Transferencia')], default='VENTA', max_length=100)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productocatalogo')),
            ],
        ),
    ]
