# Generated by Django 6.0 on 2025-12-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('solicitante', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cerrada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productocatalogo')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.requisicion')),
            ],
        ),
    ]
